version: '2'

services: 
  google_mmm:
    image: u03013112/google_mmm:v1
    container_name: 'google_mmm'
    tty: true
    volumes:
        - ../:/src:cached
    working_dir: /src/
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"